#! /usr/bin/env sh

set -eux

DOTFILES_DIR=$(dirname "$0")

if command -v apt-get; then
  if ! [ $(id -u) = 0 ]; then
    sudo apt-get update
    sudo apt-get install less zsh curl wget tar vim -y
  else
    apt-get update
    apt-get install less zsh curl wget tar vim -y
  fi
fi

if command -v apk; then
  if ! [ $(id -u) = 0 ]; then
    sudo apk add less zsh curl wget tar vim
  else
    apk add less zsh curl wget tar vim
  fi
fi

if [ ! -e ~/.oh-my-zsh ]; then
  git clone https://github.com/ohmyzsh/ohmyzsh ~/.oh-my-zsh --depth 1
fi

mkdir -p ~/.git
cp $DOTFILES_DIR/git/ignore ~/.git/.ignore
cp $DOTFILES_DIR/gitconfig ~/.gitconfig
cp $DOTFILES_DIR/zshrc ~/.zshrc
