#! /usr/bin/env sh

set -eux

sudo apt-get update
sudo apt-get install less zsh curl vim -y

if [ ! -e ~/.oh-my-zsh ]; then
  git clone https://github.com/ohmyzsh/ohmyzsh ~/.oh-my-zsh --depth 1
fi

mkdir -p ~/.git
cp git/ignore ~/.git/.ignore
cp gitconfig ~/.gitconfig
cp zshrc ~/.zshrc

sudo chsh $(whoami) -s $(which zsh)

if [ -z ${CHE_WORKSPACE_NAMESPACE+x} ]; then
  # non che
  true
else
  # che
  git config --global core.editor vim
  git config --global commit.gpgsign false
fi
