#! /usr/bin/env sh

set -eux

wget -qO - https://apt.thoughtbot.com/thoughtbot.gpg.key | sudo apt-key add -
echo "deb https://apt.thoughtbot.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/thoughtbot.list
sudo apt-get update
sudo apt-get install rcm less zsh curl -y

git clone https://github.com/ohmyzsh/ohmyzsh ~/.oh-my-zsh --depth 1

RCRC=$(pwd)/rcrc rcup -d $(pwd)
